global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "reticulum"
    scheme: https
    tls_config:
      insecure_skip_verify: true
    metrics_path: /metrics
    static_configs:
      - targets: ["reticulum:4000"]
        labels:
          service: reticulum
